name: JMeter Test Report Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  jmeter-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip default-jre
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.zip
          unzip apache-jmeter-5.6.3.zip
          mv apache-jmeter-5.6.3 jmeter

      - name: Run JMeter Test and Generate HTML Report
        run: |
          mkdir results
          ./jmeter/bin/jmeter -n -t AMAZON_PERFORMANCE.jmx -l results/result.jtl -e -o results/html-report

      - name: Deploy HTML Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./results/html-report
          publish_branch: gh-pages
          force_orphan: true
